version: "3.8"

services:

  configserver:
    image: yash1gangrade/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - yash1gangrade-network

  eurekaserver:
    image: yash1gangrade/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - yash1gangrade-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  loans:
    image: yash1gangrade/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - yash1gangrade-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  accounts:
    image: yash1gangrade/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - yash1gangrade-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  cards:
    image: yash1gangrade/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - yash1gangrade-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  gatewayserver:
    image: yash1gangrade/gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - yash1gangrade-network
    depends_on:
      - configserver
      - eurekaserver
      - cards
      - loans
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

networks:
  yash1gangrade-network: